# Generated by Django 4.1.1 on 2023-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change blog visibility', verbose_name='blog visibility'),
        ),
    ]
