# Generated by Django 4.1.1 on 2023-04-08 21:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_blogpost_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of your company', max_length=600, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('instagram_link', models.URLField(blank=True, help_text='link to your instagram', null=True)),
                ('twitter_link', models.URLField(blank=True, help_text='link to your twitter', null=True)),
                ('facebook_link', models.URLField(blank=True, help_text='link to your facebook', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text="link to your what's app", null=True)),
                ('about_text', ckeditor.fields.RichTextField(help_text='what is your company like?', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='your phone number', max_length=10, null=True)),
                ('other_number', models.CharField(blank=True, help_text='other phone number', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, help_text='your email', max_length=254, null=True)),
                ('district', models.CharField(help_text='where are you based?', max_length=300, null=True)),
                ('location', models.CharField(help_text='eg area 18', max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_cats', to='store.category'),
        ),
    ]
