# Generated by Django 4.1.1 on 2023-04-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_about_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
