# Generated by Django 4.1.1 on 2023-04-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_about_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About  Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
