# Generated by Django 4.1.1 on 2023-04-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recieved', 'Recieved'), ('On Delivery', 'On Delivery'), ('Delivered', 'Delivered')], max_length=300, null=True),
        ),
    ]
